pref('extensions.secureLogin.shortcut', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin.searchLoginsOnload',true);
pref('extensions.secureLogin.skipDuplicateActionForms',true);
pref('extensions.secureLogin.highlightColor','#FF9900');
pref('extensions.secureLogin.highlightOutlineStyle','solid');
pref('extensions.secureLogin.highlightOutlineWidth',"1px");
pref('extensions.secureLogin.highlightOutlineRadius',"5px");
pref('extensions.secureLogin.autoSubmitForm',false);
pref('extensions.secureLogin.javascriptProtection',true);
pref('extensions.secureLogin.exceptionList','');
pref('extensions.secureLogin.helpURL', "");
//pref("signon.autofillForms", false);
