pref('extensions.secureLogin@blueimp.net.shortcut', 'chrome://secureLogin/locale/secureLogin.properties');
pref('extensions.secureLogin.showDoorhangerLogin', true);
pref('extensions.secureLogin.showDoorhangerLogin.dismissed', true);
pref('extensions.secureLogin@blueimp.net.searchLoginsOnload',true);
pref('extensions.secureLogin@blueimp.net.skipDuplicateActionForms',true);
pref('extensions.secureLogin@blueimp.net.highlightColor','#FF9900');
pref('extensions.secureLogin@blueimp.net.highlightOutlineStyle','solid');
pref('extensions.secureLogin@blueimp.net.highlightOutlineWidth',"1px");
pref('extensions.secureLogin@blueimp.net.highlightOutlineRadius',"5px");
pref('extensions.secureLogin@blueimp.net.autoSubmitForm',false);
pref('extensions.secureLogin@blueimp.net.javascriptProtection',true);
pref('extensions.secureLogin@blueimp.net.exceptionList','');
//pref("signon.autofillForms", false);
